# This workflow checks if a pull request has the "lgtm" label before it can be merged.
name: Require LGTM Label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, reopened]

jobs:
  check-lgtm-label:
    name: Label_Validator
    runs-on: ubuntu-latest
    steps:
      - name: Handle /lgtm comment command
        if: github.event_name == 'issue_comment' && github.event.comment.body == '/lgtm'
        uses: actions/github-script@v7
        with:
          script: |
            const commentUser = context.payload.comment.user.login;
            const prNumber = context.payload.issue.number;

            // Check if the issue is a pull request
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            if (!pr) {
              console.log("Comment is not on a pull request.");
              return;
            }

            // Check if commenter is a requested reviewer or has write access
            const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: commentUser
            });

            if (permission.permission !== 'write' && permission.permission !== 'admin' && permission.permission !== 'maintain') {
              console.log(`User ${commentUser} does not have permission to apply lgtm.`);
              return;
            }

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['lgtm']
            });

            console.log(`Applied 'lgtm' label via comment by ${commentUser}.`);
            
      - name: Remove "lgtm" label on new commits
        if: github.event.action == 'synchronize'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const labels = context.payload.pull_request.labels.map(label => label.name);

            if (labels.includes('lgtm')) {
              console.log("Removing 'lgtm' label due to new commit.");
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                name: 'lgtm'
              });
            }

      - name: Check for "lgtm" label
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });

            const labelNames = labels.map(label => label.name);
            if (!labelNames.includes("lgtm")) {
              core.setFailed("Pull Request must have the 'lgtm' label before it can be merged.");
            }
