# This workflow checks if a pull request has the "lgtm" label before it can be merged.
name: Require LGTM Label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, reopened]

jobs:
  check-lgtm-label:
    name: Label_Validator
    runs-on: ubuntu-latest
    steps:
      - name: Check for "lgtm" label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            if (!labels.includes("lgtm")) {
              core.setFailed("Pull Request must have the 'lgtm' label before it can be merged.");
            }
